JenryHenry/Hungie-Bois

assets/script.js
assets/style.css
index.html

i changed the div id from food selection to options

added options

---

assets/style.css
landingpage.html

add css styling for background image

Background Image CSS

---

assets/style.css
mainpage.html

and added placeholder text for the weather tile. Moved the modal from the deleted html page, and updated it's appearance to match the new color scheme.

Adjusted tiles sizes for mainpage.html

---

assets/script.js
mainpage.html

Added JS to make the modal close and expose the mainpage.html behind it.

Javascript modal

---

chosenrestaurantpage.html
mainpage.html

add Chosen Restaurant element and restaurant address element.
fix parameters button to be centered when screen size changes

ChosenRestaurantHTML additions

---

assets/script.js
mainpage.html

Added API_KEY variables, and variables to target the weather tile in HTML and update that information...once we have the google places API ready. Also added some text to the mainpage.html weather tile.

Js weather card

---

assets/script.js
mainpage.html

Added api keys for both APIs.

---

assets/script.js
chosenrestaurantpage.html
mainpage.html

Added functionality to make the modal come back up when the Search Parameters button is clicked on the mainpage.html

Reload modal

---

assets/script.js
chosenrestaurantpage.html
mainpage.html

Added modal to chosenrestaurantpage.html so that the modal can be reloaded from here. The modal is disabled by default, and only becomes active once the Search Parameters button is clicked.

Chosenrestaurantpage reload modal

---

assets/script.js
chosenrestaurantpage.html
mainpage.html

Added functionality to modal. Checkboxes now store referenceable data for the Google Places API to obtain and search for in local storage.

Modal localstorage

---

.gitignore
assets/script.js
assets/style.css
chosenrestaurantpage.html
mainpage.html

Deleted unnecessary files (.env, .gitignore, chosenrestaurant.style), and added the getUserLocation function using OpenWeather API.

Get user location

---

chosenrestaurantpage.html
mainpage.html

Added weather tile functionality to chosenrestaurant page. Adjusted center tile size on mainpage.

Updated chosenrestaurant page w/ weather tile functionality

---

assets/.env
assets/script.js
mainpage.html

Add checkbox functionality. Store checkbox user input in an object called "checkedBoxes" and stores that object in local storage.
Additionally, if user clicks none of the checkboxes, an alert pops up prompting them to click at least one checkbox.

Checkboxes

---

assets/style.css
chosenrestaurantpage.html
mainpage.html

Copied updated modal HTML from the mainpage.html to chosenrestaurant.html. Kind of fixed formatting of the input button and the associated text.

Fixed Modal Formatting

---

assets/script.js
mainpage.html

Add "generateRandomRestaurant" function.
- Generates a random restaurant and populates Random Restaurant element with that random restaurant's name.
Fix bug where PlacesAPI was being called twice
-note: for the bug to be fixed, the API call had to be removed from part of the modal function. 
-Consequence: ONLY clicking the "use current location" button will activate the radio input function and the API call function.
Clicking the 'x' in the corner of the modal or clicking outside the modal WILL NOT activate those functions.
Recommendation: Change the user Location button's text content to say "OK" or "Submit" so that the user knows that they have to click the button for the site to generate a random restaurant.

Random restaurant function

---

assets/script.js
assets/style.css
mainpage.html

-change location button to "submit"
-add question mark to random restaurant element.
-add "do you want" before random restaurant element.

location button change

---

assets/script.js
mainpage.html

yass button now displays restaurant and restaurant address when clicked.
-hides yass/pass tile and displays restaurant info tile

add yass button functionality

---

assets/script.js
assets/style.css
index.html

Added media query to make make modal choices go vertical on screens smaller than 426px, and stay horizontal on screen 426px or larger.

Modal media query

---

assets/script.js
assets/style.css
index.html

Restructured javascript file by moving global variables to the top of the page and sorting the order the functions appear to make more sense. Added underline to title text in Weather and Passed tiles. Added scroll functionality to Passed tile so that it doesn't grow downward for forever. Removed excess code that was commented out, and console.logs. Added code comments to all files.

Restructured JS, Comments, Scroll Bar, Removed Excess Code. 

---

assets/script.js
assets/style.css
index.html

Changed filepath on line 4 of CSS. It was incorrect.

Background image
